# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Xilinx/Xilinx_Training/ProyectUart/ProjectUart.cache/wt [current_project]
set_property parent.project_path C:/Xilinx/Xilinx_Training/ProyectUart/ProjectUart.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo-z7-20:part0:1.0 [current_project]
set_property ip_output_repo c:/Xilinx/Xilinx_Training/ProyectUart/ProjectUart.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Xilinx/Xilinx_Training/ProyectUart/ProjectUart.srcs/sources_1/bd/designbd_uart/hdl/designbd_uart_wrapper.v
add_files C:/Xilinx/Xilinx_Training/ProyectUart/ProjectUart.srcs/sources_1/bd/designbd_uart/designbd_uart.bd
set_property used_in_implementation false [get_files -all c:/Xilinx/Xilinx_Training/ProyectUart/ProjectUart.srcs/sources_1/bd/designbd_uart/ip/designbd_uart_processing_system7_0_1/designbd_uart_processing_system7_0_1.xdc]
set_property used_in_implementation false [get_files -all C:/Xilinx/Xilinx_Training/ProyectUart/ProjectUart.srcs/sources_1/bd/designbd_uart/designbd_uart_ooc.xdc]
set_property is_locked true [get_files C:/Xilinx/Xilinx_Training/ProyectUart/ProjectUart.srcs/sources_1/bd/designbd_uart/designbd_uart.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Xilinx/Xilinx_Training/Zybo-Z7-Master.xdc
set_property used_in_implementation false [get_files C:/Xilinx/Xilinx_Training/Zybo-Z7-Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top designbd_uart_wrapper -part xc7z020clg400-1


write_checkpoint -force -noxdef designbd_uart_wrapper.dcp

catch { report_utilization -file designbd_uart_wrapper_utilization_synth.rpt -pb designbd_uart_wrapper_utilization_synth.pb }
