# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Xilinx/Xilinx_Training/Zybo-Z7-Master.xdc

# Block Designs: bd/designbd_uart/designbd_uart.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==designbd_uart || ORIG_REF_NAME==designbd_uart}]

# IP: bd/designbd_uart/ip/designbd_uart_processing_system7_0_1/designbd_uart_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==designbd_uart_processing_system7_0_1 || ORIG_REF_NAME==designbd_uart_processing_system7_0_1}]

# XDC: bd/designbd_uart/designbd_uart_ooc.xdc
