# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Xilinx/Xilinx_Training/ProyectUart/ProjectUart.srcs/sources_1/bd/designbd_uart/ip/designbd_uart_processing_system7_0_1/designbd_uart_processing_system7_0_1.xci
# IP: The module: 'designbd_uart_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/Xilinx_Training/ProyectUart/ProjectUart.srcs/sources_1/bd/designbd_uart/ip/designbd_uart_processing_system7_0_1/designbd_uart_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'designbd_uart_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/Xilinx/Xilinx_Training/ProyectUart/ProjectUart.srcs/sources_1/bd/designbd_uart/ip/designbd_uart_processing_system7_0_1/designbd_uart_processing_system7_0_1.xci
# IP: The module: 'designbd_uart_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/Xilinx_Training/ProyectUart/ProjectUart.srcs/sources_1/bd/designbd_uart/ip/designbd_uart_processing_system7_0_1/designbd_uart_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'designbd_uart_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
